version: '3'
services:
  db:
    container_name: course-erp-db
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5500:5432'
    volumes:
      - ./docker-volumes/course-erp-db:/var/lib/postgresql/data






