spring:
  datasource:
    url: jdbc:postgresql://localhost:5500/course_erp_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false #true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

security:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvvi8AVDIZqvlC3l2hRejuXLyMEcj/WgRNihm2P5GOCHQPkgX6IjVDhxBijOlWaQKv2HGMNNsxDNL7HHlDM3nku2yc5WwSHB5VadBYYFjJd90SE859jdxifN4jYCjDK0qGshaWQsOAAwG7uUJSZmBmzCsAERHNBnQyXsBNr2vtNO4Paq5uMHKyaMn8Mobfx7SOtFbzfsZeR4GFrH7Y3cOf9MTdx6f+MiZZ2xQydffL+A4ry1ggNTA4tF1GMLULhStOTiLlRceRS6bGLvXWmBUoIkNub/YZOQBhXocgwWNdsQ3b+Ozf6mNBRz33bOAJzC6z0pGBuw/vlPhaerKQePGZQIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC++LwBUMhmq+ULeXaFF6O5cvIwRyP9aBE2KGbY/kY4IdA+SBfoiNUOHEGKM6VZpAq/YcYw02zEM0vsceUMzeeS7bJzlbBIcHlVp0FhgWMl33RITzn2N3GJ83iNgKMMrSoayFpZCw4ADAbu5QlJmYGbMKwAREc0GdDJewE2va+007g9qrm4wcrJoyfwyht/HtI60VvN+xl5HgYWsftjdw5/0xN3Hp/4yJlnbFDJ198v4DivLWCA1MDi0XUYwtQuFK05OIuVFx5FLpsYu9daYFSgiQ25v9hk5AGFehyDBY12xDdv47N/qY0FHPfds4AnMLrPSkYG7D++U+Fp6spB48ZlAgMBAAECggEAW9VKuys4oz7H7uOi3c+HWNdwpUygfuw7UprNEk38QGPqOvj6HkUmhxmJXscFHX0n+e4vmy0gYZz1RqdiaOzfDiWlqbVyxvLnNgwvAY9xuTWiOl921PLGc3sUHp+cSK1A0Q5FfAo32kfuUZTsCWt7CsC2BY7P2rsLTsgKxmMjCkXrB+bTg/xC/+l7c/pTK4hecP0Osxce02v8G8fcKgq6Fuzv1Xjb1tuXgBAoutM/0kiTS7NeOcwZopT/CVOulikntEvRHVh4VUW++nBQOUvXQpMshebcFso4l6p1VwEk1CWKASnO7z7Lwd8QpzTMkbb85Uu8N9lhqjjk8tSVR3zlwQKBgQD8qMkL22Z/ntYLg4fAe72SI4ouvOmMBWoB4xABje5bw7tUIJYAwAfKabKaS8aPY7VaIJJI3Opgt4MAUCF8bdKPryFsNvHltqyQcVLsn8+wPM+kKPEyL3qGoZLmgxMXZCvHD2hcibXDKb0uaQUfe8DEhovTOOUm3ihxf1XtaX6vEQKBgQDBfyUv3ll1Oi63JvSXe5sSJty7tyvnlOdmILTD34B+JgSaakZ9OHtJu/SRB11c+h3gNCyFZgPF7AGKn8gIrHsG68ZRjRFg9pB/rI65gX/lWMM9lA+9ZynhjRU4YEiI/TAlIoc/VIYYC2yA48kUguPuSeiWRhD2a639kciMlpzKFQKBgQDVFeS5Q0imyWbsPvn2tGWlIqQf1uOBW++Tt9R/+xvT+Le8s97OsyXe6FXhG5dSx1zjriSxnt9swliRowMa1eSHmcQuaAiLHA1dpLWzKvUWRbM5V+5TzQchFJO4JUOsrqbdM3lo0huhhUowIhJYAx8IoBC9C3b32NVzI1ls6VQWgQKBgChBDTlyJmYu3n0Xy5agDliuYQlkR+v7nFAwyapeGtsjiZ2eMl/mmi9yvKRXReML3Z9A+2odGPfZ61AtgW3chBOihTV+BXmIkfMdsOuCt1q9JpDu9n9OsPXNZfa+gRiOo692CXDxYpwp9D60JKbxu/1cvthUZz78k8vGwlQNGT0pAoGARj2CFY1Cmg9cvy3ceoIZN1Vm+1XwmKSq5xAm/ASZi4IxaePxEKnQFuk/K8Yc1NBdlnYzC6W8N1lmVIaMCZ4UOZhxYUmZ6Jw5AEhWSeFd0h6WbtOGpXmjCKRKfsvjLbsQmG1iFQReJzdJh0cUOR2Ze0oQRTiqWTAF4I36iD/SUIs=
    access-token-validity-time: 1800000
    refresh-token-validity-time: 86400000

server:
  error:
    include-message: always