spring:
  datasource:
    url: jdbc:postgresql://localhost:5500/course_erp_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

security:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzZA1H/CDqb4H3ffuG92+Q8uF651UvYnyApaZ4YrSEG2oB26m5WDdpbfEYdPVYAk5ZVoktLsCrWDYzb0b5oP5rFkdQTAhPjz4QcsFsy6uJsThmFYJgRFcBFn2q06azSbv6ifIk5WcBnzB2JB/Uf24wQBaRt8F18dA52u7h2B6L3iqeG0luJDQBDPKT7T4aGfoZ3AWKqW+Ul+vsZ7IklH1WpWNu03WEGAp6bK9jzHYhCXGNvUczsP134lhs6tYaz8E8jzihXVFGxX96/7t57pCOFryRNTS/NLU8mu+HAzqk9ptqObk1RPGgttTI76jPahTFOvmjrCR0q6c0kmu0SwCgwIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDNkDUf8IOpvgfd9+4b3b5Dy4XrnVS9ifIClpnhitIQbagHbqblYN2lt8Rh09VgCTllWiS0uwKtYNjNvRvmg/msWR1BMCE+PPhBywWzLq4mxOGYVgmBEVwEWfarTprNJu/qJ8iTlZwGfMHYkH9R/bjBAFpG3wXXx0Dna7uHYHoveKp4bSW4kNAEM8pPtPhoZ+hncBYqpb5SX6+xnsiSUfValY27TdYQYCnpsr2PMdiEJcY29RzOw/XfiWGzq1hrPwTyPOKFdUUbFf3r/u3nukI4WvJE1NL80tTya74cDOqT2m2o5uTVE8aC21MjvqM9qFMU6+aOsJHSrpzSSa7RLAKDAgMBAAECggEAYpgjuuWHqP8B0/eKJ6h0DR1NZuSH0/8Zah9kwDZuqb2GpcXvW75ZoRXipc9OHOlfs5qIV30I/DKi2g81lhs/wefeLbmRgEILCrd/TOF7WxH8aC4AEf1LBrVFqAWkHvjpgoRBYnQUKVJmQWKRBrjsh/mM00g+C7BAk57rC7P89s4LMziRUZ1YgAZxGHN4M70Ch731cwDO19qs6l1QQBiEP+WE4Fg5SZ6nXiS3UV8jQscCHwgfQOM4wfDTX58B0gVr1Hom3Jba8ljtr8tKCflsZFbXJ1P0SW5mEHszA/cAgKfcomfAeuf6b7Q/XfcjwZRiz74f9oK2r8qQGBPiwGKklQKBgQD3y0U5N8BbmpiigE7bg+tCHs2iWFM7YpqTEWWN2JAz86shaflyKcDCFiyNX5Kp6PNcuoKnW86a8Fkqy5SQCtozkGnAUUKH2/9f/zF6iS35ENf81RgYXWY1nz9jmHTnube4FfNoetbflzXJxbUv7ul6P5a2yXNcuaFH5y7JaVxxtwKBgQDUXuqu8aV9O9ULGDtSdYuSUf8UI9frHZfQ1wQFxd11izVDBhSpNYcsNFM/KIt9BOG4akNkKbfRDmAzlIOw8xfJk6aluOXNCENEXqy0S/BYoVWXdqitViIiwKYy2b4lgiOLtwCTCndNF39ZFCpD/Pbuyfr0oWMRbi5el682DATFlQKBgE8EyE9lwvazRwdTCVKhL82HCyZBKlGesRJDEvJ35AxdIO5n3/8S54A9F/oBR0Ddo3WnmHCMK0dna9fk0bxZaZnV7JNClofClR5kv7+GrV1mjKn4vlVOu4BQByPYgzc+FyMiBNwFiC4HB0UPwibF9jhgvMwPU7V3EMJgK6BY8/zjAoGAbAze2qOXz1/hxQNPK2Ui3g9Z+KVD9hvYYikDouxJAMUTFEbDvFO/sn3s3PWEAte5AFsQbqXLIFJwH84wMpd8QtMctrScNvU9REvnEtSQNIfhRG7a41Yvh/78kGK4m9zauPsjD60DhfWulWPtHSpXeKbLSCvUe8nTTc1fF+CFjQECgYEAiGZ2AtEAF3ZaB5CDOCc3ODaoLz5E1RD94ETuacVOwJwsc8LRH/Qmt4nEVD61qUTjYT6AGJKOXZJKQZ3F8P5Kn2ImjR5SGNrDVB5gVD5KeIUxv4GZAxqVKuhhVM8UHYZRottUQ/9Tc093lGMo6S9fOCITpxjXM485+PFCjE4nF9w=
    access-token-validity-time: 1800000
    refresh-token-validity-time: 86400000

server:
  error:
    include-message: always