# Use an official PostgreSQL image from Docker Hub
FROM postgres:16.0

# Set the environment variables for the PostgreSQL instance
ENV POSTGRES_DB=course-erp
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root

